### ISSUE TITLE
Create a basic screen for Pull Requests metrics

### ISSUE THREAD

**Issue by bparish628** [jakeharding/repo-health#20]
Use the following api to create a basic pull request metric page.
https://github.com/jakeharding/repo-health/blob/dev/docs/rest_api/PullRequests.md

**Comment by jakeharding** [comment]
As you develop the pull request front end, you may discover some metrics not included yet.  Add a note to the PullRequests.md doc to keep track so we can possibly add them.  For instance, I found we may want to include pull requests to an upstream repo.
