### ISSUE TITLE
Update UI Framework

### ISSUE THREAD

**Issue by bparish628** [jakeharding/repo-health#21]
@jakeharding 

I've been thinking it would be cooler to user something other than bootstrap

I like bootstrap, but I like material design better. How do you feel about incorporating one of these?

http://materializecss.com/
https://material.angularjs.org/

**Comment by jakeharding** [comment]
I am good with what you are most comfortable developing with.  Feel free to use the tools you are most productive or most comfortable with.

**Comment by jakeharding** [comment]
This seems complete so it's getting closed.
