### ISSUE TITLE
Return URLs to front end when appropriate.

### ISSUE THREAD

**Issue by jakeharding** [jakeharding/repo-health#23]
@bparish628 
I could return the URLs needed for stats resources if it will help any.

**Comment by bparish628** [comment]
I don't think we would need this. I can't image an instance where I would want urls back (unless of course it is changing often). The ui will just hit the resource that the page expects.

Maybe you had a different view of it?

**Comment by jakeharding** [comment]
Close this as we discussed it and it isn't needed.
