### ISSUE TITLE
Application not finding Repo's via URL

### ISSUE THREAD

**Issue by mshoote** [jakeharding/repo-health#59]
I followed the development setup using Docker and after setting up I ran:
   docker --version 
   docker-composure --version
and got the anticipated results docker expected.
I then ran: docker-compose up and once it completed I went to localhost:8000 and attempted the following two URL's using the application.

https://github.com/mshoote/BTJSC
https://github.com/angular/angular

After entering both separate times I got for both "Error This Repo does not exist" as seen in the screen shot below.

<img width="1280" alt="screen shot 2017-04-17 at 8 55 24 pm" src="https://cloud.githubusercontent.com/assets/25125346/25111372/41e976ce-23b0-11e7-80bc-97ea57bd1ce7.png">

And on the terminal side this is what it looked like (in screen shot below) after running the docker-compose up and then trying the two URL's in the order shown above.

<img width="1280" alt="screen shot 2017-04-17 at 8 57 11 pm" src="https://cloud.githubusercontent.com/assets/25125346/25111411/77c7beb8-23b0-11e7-92a8-cd90b8dea68d.png">

I am not sure if the URL is expected to be in a different form, or what I may be doing wrong.
Any help would be appreciated.

Docker versions below:
Docker version 17.03.1-ce, build c6d412e
docker-compose version 1.11.2, build dfed245
docker-machine version 0.10.0, build 76ed2a6

Also I am using a mac running macOS Sierra Version 10.12.2

**Comment by bparish628** [comment]
This actually can't find newer repos. This is using msr14 database, which is not current. Try using `cakephp/cakephp` or `django/django`.

**Comment by mshoote** [comment]
Okay and I see its not a full URL. Thank you for the help.

**Comment by jakeharding** [comment]
Closing this as #60 covers it.
