### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by ghost** [jakeharding/repo-health#64]
During my installation process, I encountered the following issue. Looks like it isn't accessing my METADATA in my python package. I do have Python 3.6 on my computer (Mac). Any thoughts?

[Dreizan_Error_When_Installing.txt](https://github.com/jakeharding/repo-health/files/960179/Dreizan_Error_When_Installing.txt)

**Comment by jakeharding** [comment]
This is an issue with a dependency. I believe it is fixed in the dev branch. I will be merging the dev in to master soon but could you check out the dev branch and verify it works?

**Comment by ghost** [comment]
It works on dev. Thanks!
