### ISSUE TITLE
Repository Design

### ISSUE THREAD

**Issue by germonprez** [jakeharding/repo-health#8]
A few comments on your repo: 

1) Use .md so you can get better formatting on your documents. 
2) I have no idea what this repo is for. Spell out what you are doing and what you are leveraging and contributing to. 
3) There appears to be one contributor

**Comment by bparish628** [comment]
@germonprez 
3) Contributions are based on master correct? We haven't merged our dev branch into master yet :confused:.

**Comment by germonprez** [comment]
You are right. I only looked at Master. A deeper dive into dev is still pretty heavy for @jakeharding. I know that these numbers don't tell the entire story of a project but they are the things I can look at.

**Comment by jakeharding** [comment]
Closing this because it is from Milestone 1.
